server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: JOB-SERVICE
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/job-service/**
          filters:
            - RewritePath=/jobs/(?<segment>.*), /$\{segment}

        - id: COMPANY-SERVICE
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company-service/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
